apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-grpc
  labels:
    app: go-grpc
    version: canary
  namespace: go-grpc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-grpc
      version: canary
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: go-grpc
        version: canary
    spec:
      containers:
      - image: 452402024371.dkr.ecr.us-west-2.amazonaws.com/go-grpc
        imagePullPolicy: Always
        name: go-grpc
        ports:
            - containerPort: 3041
              protocol: TCP
